#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "wallet release"

on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "WALLET_WEB_IMAGE_PREFIX"=ghcr.io/trustbloc/wallet-web >> $GITHUB_ENV
          echo "WALLET_SERVER_IMAGE_PREFIX"=ghcr.io/trustbloc/wallet-server >> $GITHUB_ENV
          echo '//npm.pkg.github.com/:_authToken=${DOCKER_PASSWORD}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc:registry=https://npm.pkg.github.com' >> ~/.npmrc
          make wallet-web
        env:
          DOCKER_USER: ${{ secrets.CR_USER }}
          DOCKER_PASSWORD: ${{ secrets.CR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push wallet-server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/wallet-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.15
            GO_VER=1.17
          push: true
          tags: |
            ${{ env.WALLET_SERVER_IMAGE_PREFIX }}:${{ env.IMAGE_TAG }}
            ${{ env.WALLET_SERVER_IMAGE_PREFIX }}:latest

      - name: Build and Push wallet-web image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/wallet-web/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.15
            GO_VER=1.17
          push: true
          tags: |
            ${{ env.WALLET_WEB_IMAGE_PREFIX }}:${{ env.IMAGE_TAG }}
            ${{ env.WALLET_WEB_IMAGE_PREFIX }}:latest
